
export const TODO_DEMO_LOAD_TODOS = 'TODO_DEMO/LOAD_TODOS';
export const TODO_DEMO_TOGGLE_DONE = 'TODO_DEMO/TOGGLE_DONE';
export const TODO_DEMO_REMOVE_TODO = 'TODO_DEMO/REMOVE_TODO';
export const TODO_DEMO_ADD_TODO = 'TODO_DEMO/ADD_TODO';
